// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $bio from "./routes/bio.tsx";
import * as $fashion from "./routes/fashion.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $productions_alebrijes from "./routes/productions/alebrijes.tsx";
import * as $productions_happy_days from "./routes/productions/happy-days.tsx";
import * as $productions_play_about_my_father from "./routes/productions/play-about-my-father.tsx";
import * as $theater from "./routes/theater.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $LoadAwareImage from "./islands/LoadAwareImage.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/bio.tsx": $bio,
    "./routes/fashion.tsx": $fashion,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/productions/alebrijes.tsx": $productions_alebrijes,
    "./routes/productions/happy-days.tsx": $productions_happy_days,
    "./routes/productions/play-about-my-father.tsx":
      $productions_play_about_my_father,
    "./routes/theater.tsx": $theater,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/LoadAwareImage.tsx": $LoadAwareImage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
