// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $bio from "./routes/bio.tsx";
import * as $fashion from "./routes/fashion.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $productions_a_midsummer_nights_dream_2022 from "./routes/productions/a-midsummer-nights-dream-2022.tsx";
import * as $productions_alebrijes from "./routes/productions/alebrijes.tsx";
import * as $productions_blond_on_a_bum_trip from "./routes/productions/blond-on-a-bum-trip.tsx";
import * as $productions_happy_days from "./routes/productions/happy-days.tsx";
import * as $productions_mr_burns_a_post_electric_play from "./routes/productions/mr-burns-a-post-electric-play.tsx";
import * as $productions_or from "./routes/productions/or.tsx";
import * as $productions_play_about_my_father from "./routes/productions/play-about-my-father.tsx";
import * as $productions_sherlock_christmas_carol from "./routes/productions/sherlock-christmas-carol.tsx";
import * as $productions_shrew_sunvalley from "./routes/productions/shrew-sunvalley.tsx";
import * as $productions_three_sisters from "./routes/productions/three-sisters.tsx";
import * as $productions_year_of_magical_thinking from "./routes/productions/year-of-magical-thinking.tsx";
import * as $testimonials from "./routes/testimonials.tsx";
import * as $theater from "./routes/theater.tsx";
import * as $LoadAwareImage from "./islands/LoadAwareImage.tsx";
import * as $ReviewCarousel from "./islands/ReviewCarousel.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/bio.tsx": $bio,
    "./routes/fashion.tsx": $fashion,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/productions/a-midsummer-nights-dream-2022.tsx":
      $productions_a_midsummer_nights_dream_2022,
    "./routes/productions/alebrijes.tsx": $productions_alebrijes,
    "./routes/productions/blond-on-a-bum-trip.tsx":
      $productions_blond_on_a_bum_trip,
    "./routes/productions/happy-days.tsx": $productions_happy_days,
    "./routes/productions/mr-burns-a-post-electric-play.tsx":
      $productions_mr_burns_a_post_electric_play,
    "./routes/productions/or.tsx": $productions_or,
    "./routes/productions/play-about-my-father.tsx":
      $productions_play_about_my_father,
    "./routes/productions/sherlock-christmas-carol.tsx":
      $productions_sherlock_christmas_carol,
    "./routes/productions/shrew-sunvalley.tsx": $productions_shrew_sunvalley,
    "./routes/productions/three-sisters.tsx": $productions_three_sisters,
    "./routes/productions/year-of-magical-thinking.tsx":
      $productions_year_of_magical_thinking,
    "./routes/testimonials.tsx": $testimonials,
    "./routes/theater.tsx": $theater,
  },
  islands: {
    "./islands/LoadAwareImage.tsx": $LoadAwareImage,
    "./islands/ReviewCarousel.tsx": $ReviewCarousel,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
