export interface Production {
  show: string;
  theater: string;
  location: string;
  date: string;
  corrected?: boolean;
  notes?: string;
}

export const PRODUCTIONS: Production[] = [
  {
    "show": "A Year of Magical Thinking",
    "theater": "Northwest Classical Theatre Collaborative",
    "location": "Portland OR",
    "date": "2024-10",
  },
  {
    "show": "Blond on a Bum Trip",
    "theater": "Fuse Theatre Ensemble",
    "location": "Portland OR",
    "date": "2024-05",
  },
  {
    "show": "The Play About My Father",
    "theater": "Fuse Theatre Ensemble",
    "location": "Portland OR",
    "date": "2024-04",
  },
  {
    "show": "Happy Days",
    "theater": "Northwest Classical Theatre Collaborative",
    "location": "Portland OR",
    "date": "2023-08",
  },
  {
    "show": "Mr Burns a Post Electric Play",
    "theater": "Reed College Theatre Department",
    "location": "Portland OR",
    "date": "2022-10",
  },
  {
    "show": "A Midsummer's Night Dream",
    "theater": "Laughing stock Theatre",
    "location": "Sun Valley ID",
    "date": "2022-08",
  },
  {
    "show": "A Christmas Carol",
    "theater": "Portland Playhouse",
    "location": "Portland OR",
    "date": "2019-11",
  },
  {
    "show": "Comedy of Errors",
    "theater": "Laughing Stock Theatre",
    "location": "Sun Valley ID",
    "date": "2019-08",
  },
  {
    "show": "A Christmas Carol",
    "theater": "Portland Playhouse",
    "location": "Portland OR",
    "date": "2018-11",
  },
  {
    "show": "¡Alebrijes! A Día de Muertos Tale",
    "theater": "Milagro Theatre",
    "location": "Portland OR",
    "date": "2018-10",
  },
  {
    "show": "Shrew",
    "theater": "Laughing stock Theatre",
    "location": "Sun Valley ID",
    "date": "2018-08",
  },
  {
    "show": "Cabaret",
    "theater": "Fuse Theater Ensemble",
    "location": "Portland OR",
    "date": "2018-05",
  },
  {
    "show": "The Pride",
    "theater": "Defunkt Theatre",
    "location": "Portland OR",
    "date": "2018-02",
  },
  {
    "show": "Three Sisters",
    "theater": "Northwest Classical Theatre Collaborative",
    "location": "Portland OR",
    "date": "2018-01",
  },
  {
    "show": "Ruddigore",
    "theater": "Mocks Crest",
    "location": "Portland OR",
    "date": "2016-06",
  },
  {
    "show": "The Amish Project",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2016-04",
  },
  {
    "show": "Sense and Sensibility",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2016-02",
  },
  {
    "show": "Midsummer Night's Dream",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2015-11",
  },
  {
    "show": "OR",
    "theater": "Third Rail Repertory Theater",
    "location": "Portland OR",
    "date": "2015-09",
  },
  {
    "show": "Waiting For Godot",
    "theater": "Northwest Classical Theatre Collaborative",
    "location": "Portland OR",
    "date": "2015-09",
  },
  {
    "show": "HMS Pinafore",
    "theater": "Mocks Crest",
    "location": "Portland OR",
    "date": "2015-06",
  },
  {
    "show": "Really Really",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2015-04",
  },
  {
    "show": "Romeo and Juliet",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2015-02",
  },
  {
    "show": "6 Characters",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2014-11",
  },
  {
    "show": "Buried Child",
    "theater": "Profile Theater",
    "location": "Portland OR",
    "date": "2014-05",
  },
  {
    "show": "A Midsummer Night's Dream",
    "theater": "Portland State University Music Department",
    "location": "Portland OR",
    "date": "2014-04",
  },
  {
    "show": "Opus 3: After Strindberg",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2014-04",
  },
  {
    "show": "One Flea Spare",
    "theater": "Shaking the Tree",
    "location": "Portland OR",
    "date": "2014-03",
  },
  {
    "show": "The Glass Menagerie",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2014-02",
  },
  {
    "show": "Eyes for Consuela",
    "theater": "Profile Theater",
    "location": "Portland OR",
    "date": "2014-01",
  },
  {
    "show": "Dog See God",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2013-11",
  },
  {
    "show": "Xmas Unplugged",
    "theater": "Artists Repertory Theater",
    "location": "Portland OR",
    "date": "2013-11",
  },
  {
    "show": "The Big Meal",
    "theater": "Artists Repertory Theater",
    "location": "Portland OR",
    "date": "2013-09",
  },
  {
    "show": "Taming of the Shrew",
    "theater": "Portland Shakespeare Project",
    "location": "Portland OR",
    "date": "2013-07",
  },
  {
    "show": "Winter's Tale",
    "theater": "Northwest Classic Theater Company",
    "location": "Portland OR",
    "date": "2013-04",
  },
  {
    "show": "Suburbia",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2013-04",
  },
  {
    "show": "Blood Knot",
    "theater": "Profile Theater",
    "location": "Portland OR",
    "date": "2013-03",
  },
  {
    "show": "Rosencrantz and Guildenstern Are Dead",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2013-02",
  },
  {
    "show": "Road to Mecca",
    "theater": "Profile Theater",
    "location": "Portland OR",
    "date": "2013-01",
  },
  {
    "show": "A Bright Room Called Day",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2012-11",
  },
  {
    "show": "Seven Guitars",
    "theater": "Artists Repertory Theatre",
    "location": "Portland OR",
    "date": "2012-09",
  },
  {
    "show": "Master Harold and the Boys",
    "theater": "Profile Theater",
    "location": "Portland OR",
    "date": "2012-09",
  },
  {
    "show": "Lear's Follies",
    "theater": "Portland Shakespeare Project",
    "location": "Portland OR",
    "date": "2012-07",
  },
  {
    "show": "Fifth of July",
    "theater": "Profile Theater",
    "location": "Portland OR",
    "date": "2012-05",
  },
  {
    "show": "Holy Ghost",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2012-04",
  },
  {
    "show": "Galileo Galilei",
    "theater": "Portland Opera",
    "location": "Portland OR",
    "date": "2012-03",
  },
  {
    "show": "Twelfth Night",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2012-02",
  },
  {
    "show": "Reckless",
    "theater": "Portland Actors Conservatory",
    "location": "Portland OR",
    "date": "2011-11",
  },
  {
    "show": "Sherlock Holmes & the Case of the Christmas Carol",
    "theater": "Artists Repertory Theatre",
    "location": "Portland OR",
    "date": "2011-11",
  },
  {
    "show": "No Man's Land",
    "theater": "Artists Repertory Theatre",
    "location": "Portland OR",
    "date": "2011-10",
  },
  {
    "show": "As You Like It",
    "theater": "Portland Shakespeare Project",
    "location": "Portland OR",
    "date": "2011-07",
  },
  {
    "show": "L'Enfant et les Sortilèges",
    "theater": "Portland Opera",
    "location": "Portland OR",
    "date": "2011-04",
  },
  {
    "show": "The Lieutenant of Inishmore",
    "theater": "Artists Repertory Theatre",
    "location": "Portland OR",
    "date": "2011-02",
  },
  {
    "show": "Dracula",
    "theater": "Northwest Classical Theatre Company",
    "location": "Portland OR",
    "date": "2010-10",
  },
  {
    "show": "A Midsummer Night's Dream",
    "theater": "Willamette Shakespeare",
    "location": "Portland OR",
    "date": "2010-08",
  },
  {
    "show": "Trouble in Tahiti",
    "theater": "Portland Opera",
    "location": "Portland OR",
    "date": "2010-04",
  },
  {
    "show": "Becky's New Car",
    "theater": "Artists Repertory Theatre",
    "location": "Portland OR",
    "date": "2009-09",
  },
  {
    "show": "La Calisto",
    "theater": "Portland Opera",
    "location": "Portland OR",
    "date": "2009-04",
  },
];
